### ISSUE TITLE
Test infrastructure, packaging, etc. needs overhaul

### ISSUE THREAD

**Issue by tony** [jazzband/django-robots#136]
Here is all a user should need to bootstrap themselves:

```console
poetry install
```

And to test:

```console
poetry run py.test
```

It seems that `tox` is set as a _requirement_, not a supplement, to testing on the django-robots - blocking any hope of accomplishing even basic tasks. 

CI could use test matrix to get django

This is needed for #133 and for future maintainers #135

**Comment by tony** [comment]
Note: As-is, of 5.0 at 77b980c, here's how tests can be ran:

```console
env PYTHONPATH=. DJANGO_SETTINGS_MODULE=tests.settings django-admin test robots -v2
```

**Comment by jezdez** [comment]
I disagree that tox is a blocker for any of this, but I see why you'd feel that way since currently the test setup isn't using [tox-gh-actions](https://pypi.org/project/tox-gh-actions/) that allows mapping GitHub action matrix items to tox configuration and vice versa. I'd recommend doing that before flipping a table and go with Poetry.

**Comment by tony** [comment]
@jezdez I am fine with that.

I will close this and note the preference for https://pypi.org/project/tox-gh-actions/
