### ISSUE TITLE
Host

### ISSUE THREAD

**Issue by apshenychnyj** [jazzband/django-robots#25]
Hello. 
Please, if possible, add the Host field. 
SEO specialists is ask.

         User-agent: *
         Disallow: /admin/
         + --> Host: example.com
         Sitemap: http://example.com/sitemap.xml

**Comment by jezdez** [comment]
Can you provide information about that new field? You could easily override the template to add it, no?

**Comment by yakky** [comment]
@jezdez https://en.wikipedia.org/wiki/Robots_exclusion_standard#Host
Tagging as feature as it looks legit (while still addressable in the template as suggested, as a workaround)

**Comment by jezdez** [comment]
Ah, cool, hadn't seen that one yet!

**Comment by dborisov** [comment]
It is already been implemented but declined here https://github.com/jazzband/django-robots/pull/1
I think it is good solution because it helps to avoid human factor.
There is some chance to forget to add Host directive, specially on multisite setup like I have. It will be very painfull if 100+ sites will be mirrored in SERP

**Comment by yakky** [comment]
@dborisov thanks, will merge #1 soonish
