### ISSUE TITLE
Feature request: wagtail support

### ISSUE THREAD

**Issue by MikeOverkamp** [jazzband/django-robots#63]
The current django-robots implementation is dependent on django.contrib.sites. Wagtail uses its own Site model, meaning django-robots currently is not compatible with Wagtail. It would be a nice feature to be able to use django-robots for django applications that cannot make use of the 'sites' framework, such as Wagtail-sites.

**Comment by jezdez** [comment]
wagtailsites isn't a standalone Django app but an integrated [part of the core Wagtail CMS](https://github.com/torchbox/wagtail/blob/a326cd855919e9e4092b1383b611bafc840019a5/wagtail/wagtailcore/models.py#L57) which means what you're really asking is to add support for Wagtail to django-robots. Given the fact that Wagtail is only one of many Django based CMS this is out of scope of this package.

Instead I'd like to encourage you to open a ticket for Wagtail to add support for either django-robots directly (and in effect ask the [Wagtail developers/company Torchbox](https://github.com/torchbox) to contribute changes to django-robots if needed) or add a similar feature to the Wagtail core on its own. The functionality of django-robots is trivial and should be easy to port given its permissive license.

**Comment by SalahAdDin** [comment]
@MikeOverkamp so, which option have taken you?

**Comment by MikeOverkamp** [comment]
@SalahAdDin We're going to go with the solution proposed in #64. Feel free to contribute, you are more than welcome to and it would be highly appreciated.

**Comment by mheppner** [comment]
FYI this is now supported in 3.0rc1 (probably...I've never used Wagtail). You'll have to register the Wagtail sitemaps with a name, then set `ROBOTS_SITEMAP_VIEW_NAME`. See the docs for details.

**Comment by Adrian-Turjak** [comment]
I know this post is ancient... but I ended up forking this repo and just making a wagtail specific version:
https://github.com/Adrian-Turjak/wagtail-robots

While #64 would be nice, there are UI and admin side elements that make it easier to just start fresh with this codebase as a starting point. Not to mention Wagtail admin stuff doesn't do manytomany very well, so I've had to do different models for allowed and disallowed urls.

**Comment by SalahAdDin** [comment]
@Adrian-Turjak What's the different with this package?

**Comment by Adrian-Turjak** [comment]
@SalahAdDin It adds a panel to wagtail admin to manage the robots.txt and directly interfaces with the Wagtail site model. So it allows differing robot.txt rules per Wagtail site. Plus... because of how the inlinepanel logic works with clustering I had to break the url model into two separate models so I can link them to the Rule object with parentalkeys.

**Comment by Adrian-Turjak** [comment]
I did hope to just add support for Wagtail here... or even just make a minor fork, but I think there are enough differences that make a separate project easier easier, and not really that much work to maintain. But because of those changes I need to write new tests, and potentially redo the translation support.

**Comment by SalahAdDin** [comment]
@Adrian-Turjak can you add images to the documentation?

**Comment by Adrian-Turjak** [comment]
@SalahAdDin Done. :P 

I've thrown the docs on readthedocs, and added some images too:
https://wagtail-robots.readthedocs.io

Again, functionally, it's pretty much the same as this project, but integrated with Wagtail, the only extra feature I added as a dev/staging override (explained in the docs), which I may introduce here as well since it's useful.
